import type { Metadata } from "next";
import { Inter_Tight, Geist_Mono } from "next/font/google";import "./globals.css";
import { auth } from "@/auth";
import ConvexClientProvider from "./ConvexProviderWithAuth";

const inter = Inter_Tight({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <ConvexClientProvider session={session}>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
